/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Test: throw.undefinedifholewithname generated by closure capturing outer let.
// The inner function add() accesses sum from the enclosing scope.
// ldlexvar loads sum, followed by throw.undefinedifholewithname "sum" (TDZ guard).

declare function print(arg: number): string;

declare class ArkTools {
    static arkSteedCompileSync<T extends Function>(func: T): T;
}

function tdz_closure_capture(n: number): number {
    let sum = 0;
    function add(x: number): void {
        sum += x;   // ldlexvar sum → throw.undefinedifholewithname "sum"
    }
    ArkTools.arkSteedCompileSync(add);
    for (let i = 0; i < n; i++) {
        add(i);
    }
    return sum;
}

print(tdz_closure_capture(1));
print(tdz_closure_capture(5));
print(tdz_closure_capture(10));
