/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Test: throw.undefinedifholewithname generated by newobjrange using class via lexvar.
// In the loop body, new Wallet(v) loads Wallet constructor from lexical env,
// followed by throw.undefinedifholewithname "Wallet".

declare function print(arg: number): string;

declare class ArkTools {
    static arkSteedCompileSync<T extends Function>(func: T): T;
}

class Wallet {
    val: number;
    constructor(v: number) {
        this.val = v;
    }
}

function tdz_newobj_class(arr: number[]): number {
    let result = 0;
    for (let i = 0; i < arr.length; i++) {
        let obj = new Wallet(arr[i]);  // ldlexvar Wallet → throw.undefinedifholewithname "Wallet"
        result += obj.val;
    }
    return result;
}

ArkTools.arkSteedCompileSync(Wallet);
ArkTools.arkSteedCompileSync(tdz_newobj_class);

print(tdz_newobj_class([1]));
print(tdz_newobj_class([2, 3]));
print(tdz_newobj_class([4, 5, 6]));
