/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Test: throw.undefinedifholewithname generated by class reference via ldlexvar.
// The static method Counter.inc() references the class Counter via lexical env.
// ldlexvar loads Counter, followed by throw.undefinedifholewithname "Counter".

declare function print(arg: number): string;

declare class ArkTools {
    static arkSteedCompileSync<T extends Function>(func: T): T;
}

class Counter {
    static count: number = 0;

    static inc(): void {
        Counter.count++;   // ldlexvar Counter → throw.undefinedifholewithname "Counter"
    }

    static dec(): void {
        Counter.count--;   // ldlexvar Counter → throw.undefinedifholewithname "Counter"
    }
}

function tdz_class_ref(n: number, dec: boolean): number {
    for (let i = 0; i < n; i++) {
        if (dec) {
            Counter.dec();
        } else {
            Counter.inc();
        }
    }
    return Counter.count;
}

ArkTools.arkSteedCompileSync(Counter.dec);
ArkTools.arkSteedCompileSync(Counter.inc);

print(tdz_class_ref(3, false));
print(tdz_class_ref(2, true));
print(tdz_class_ref(5, false));
