/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Test: throw.undefinedifholewithname generated by module-level let accessed inside function.
// The function accesses the module-scoped counter via lexical env.
// ldlexvar loads counter, followed by throw.undefinedifholewithname "counter".

declare function print(arg: number): string;

declare class ArkTools {
    static arkSteedCompileSync<T extends Function>(func: T): T;
}

let counter = 0;

function tdz_module_let(): number {
    counter++;   // ldlexvar counter → throw.undefinedifholewithname "counter"
    return counter;
}

ArkTools.arkSteedCompileSync(tdz_module_let);

print(tdz_module_let());
print(tdz_module_let());
print(tdz_module_let());
print(counter);
