# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//arkcompiler/ets_runtime/js_runtime_config.gni")

config("rawheap_translate_public_config") {
  include_dirs = [ "$js_root/ecmascript/dfx/hprof/rawheap_translate" ]
}

rawheap_translate_sources = [
  "metadata_parse.cpp",
  "rawheap_translate.cpp",
  "serializer.cpp",
  "snapshot_merger.cpp",
  "static_rawheap_translate.cpp",
  "string_hashmap.cpp",
  "utils.cpp",
]

ohos_static_library("rawheap_translate_static") {
  sources = rawheap_translate_sources

  cflags_cc = [ "-std=c++17" ]

  public_configs = [ ":rawheap_translate_public_config" ]

  external_deps = [
    "bounds_checking_function:libsec_static",
    "cJSON:cjson_static",
  ]

  part_name = "ets_runtime"
  subsystem_name = "arkcompiler"
}

ohos_executable("rawheap_translator") {
  sources = [ "main.cpp" ]

  cflags_cc = [ "-std=c++17" ]

  deps = [ ":rawheap_translate_static" ]

  if (!ark_standalone_build) {
    branch_protector_ret = "pac_ret"
  }

  external_deps = [
    "bounds_checking_function:libsec_static",
    "cJSON:cjson_static",
  ]

  if (is_linux) {
    remove_configs = [ "//build/config:executable_config" ]
  }

  install_enable = true
  part_name = "ets_runtime"
  subsystem_name = "arkcompiler"
}
